# Numpy binary ufunc aggregates

In [33]:
import numpy as np

In [34]:
x = np.arange(1,6)
x

array([1, 2, 3, 4, 5])

### <i>reduce</i> repeatedly applies a given operation to an array until a single result remains

In [35]:
#sum all elements in x
np.add.reduce(x)

15

In [36]:
#product of all elements in x
np.multiply.reduce(x)

120

### <i>accumulate</i> stores all the intermediary results of a reduce

In [37]:
np.add.accumulate(x)

array([ 1,  3,  6, 10, 15], dtype=int32)

In [38]:
np.multiply.accumulate(x)

array([  1,   2,   6,  24, 120], dtype=int32)

### <i>outer</i> allows any ufunc to calculate the output of a crosstab of the elements

In [39]:
np.add.outer(x,x)

array([[ 2,  3,  4,  5,  6],
       [ 3,  4,  5,  6,  7],
       [ 4,  5,  6,  7,  8],
       [ 5,  6,  7,  8,  9],
       [ 6,  7,  8,  9, 10]])

In [40]:
np.multiply.outer(x,x)

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10],
       [ 3,  6,  9, 12, 15],
       [ 4,  8, 12, 16, 20],
       [ 5, 10, 15, 20, 25]])

In [53]:
#highest possible value of multiplying any of the elements in the array x
np.multiply.outer(x,x).max()

25

In [54]:
#find the index of the maximum value
np.multiply.outer(x,x).argmax()

24

### Bonus

In [42]:
J = np.random.random(100)

In [43]:
%timeit sum(J)
%timeit np.sum(J)

100000 loops, best of 3: 14.6 µs per loop
The slowest run took 9.84 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 3: 2.03 µs per loop


#### np.sum()  is much quicker because it executes the operation in compiled code

In [44]:
JJ = np.multiply.outer(J, J)

In [46]:
%timeit np.max(JJ)

The slowest run took 39.80 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 3: 6.18 µs per loop
