# Permutation and random sampling in pandas

In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.DataFrame(np.random.randint(0,10,(5,4)))
df

0  1  2  3
0  7  6  0  1
1  2  1  6  4
2  4  5  1  2
3  3  4  1  7
4  4  4  1  7

In [3]:
sampler = np.random.permutation(5)
sampler

array([2, 1, 3, 0, 4])

In [4]:
df.take(sampler)

0  1  2  3
2  4  5  1  2
1  2  1  6  4
3  3  4  1  7
0  7  6  0  1
4  4  4  1  7

In [5]:
col_sampler = np.random.permutation(2)
col_sampler

array([1, 0])

In [6]:
#sample columns
df.take(col_sampler,axis=1)

1  0
0  6  7
1  1  2
2  5  4
3  4  3
4  4  4

In [7]:
#return a copy of the data frame with rows randomly ordered
df.take(np.random.permutation(len(df)))

0  1  2  3
0  7  6  0  1
3  3  4  1  7
1  2  1  6  4
2  4  5  1  2
4  4  4  1  7

In [8]:
#take sample of three rows 
df.take(np.random.permutation(len(df))[:3])

0  1  2  3
0  7  6  0  1
3  3  4  1  7
1  2  1  6  4

In [9]:
bag= np.array([1,5,2,7,43])

In [10]:
sampler = np.random.randint(0, len(bag), size=3)
sampler

array([4, 4, 3])

In [11]:
draws = bag.take(sampler)
draws

array([43, 43,  7])

### Sample a series

In [12]:
dfsampler = np.random.randint(0,len(df[0]),size=4)
dfsampler

array([3, 2, 3, 4])

In [13]:
#can return the same row multiple times
draws = df[0].take(dfsampler)
draws

3    3
2    4
3    3
4    4
Name: 0, dtype: int32