In [44]:
import numpy as np

In [45]:
arr = np.arange(15)

In [46]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [47]:
arr.reshape((3,-1))
#passing -1 as a shape dimension will cause the shape to be inferred from the data

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [48]:
arr.reshape((-1,3))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [49]:
#Since another array's shape is a tuple, it can be passed to reshape. 
other_array = np.ones((3,5))
gg = arr.reshape(other_array.shape)
gg

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [50]:
#The opposite of reshaping is flattening or raveling
gg.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [51]:
#ravel will not return a copy of the data, however, flatten will.
gg.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [52]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [55]:
arr.reshape((5,3), order='C') 
#C as in the c programing language. C order is row major

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [57]:
arr.reshape((5,3), order='F')
#F as in the Fortran programing language. F order is column major

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

### Repeating arrays

In [58]:
arr = np.arange(3)

In [59]:
arr.repeat(3)

array([0, 0, 0, 1, 1, 1, 2, 2, 2])

In [61]:
arr.repeat([1,2,3])

array([0, 1, 1, 2, 2, 2])

In [71]:
arr = np.random.randn(2,2)

In [72]:
arr

array([[ 0.10557049,  0.17828254],
       [ 1.90767643, -1.10532562]])

In [73]:
arr.repeat(2,axis=1)

array([[ 0.10557049,  0.10557049,  0.17828254,  0.17828254],
       [ 1.90767643,  1.90767643, -1.10532562, -1.10532562]])

In [74]:
#Tiling is a shortcut for stacking copies of an array along an axis
arr

array([[ 0.10557049,  0.17828254],
       [ 1.90767643, -1.10532562]])

In [83]:
#The second parameter is the number of repetitions accross each axis
np.tile(arr,2)

array([[ 0.10557049,  0.17828254,  0.10557049,  0.17828254],
       [ 1.90767643, -1.10532562,  1.90767643, -1.10532562]])

In [84]:
x = np.tile(np.tile(arr,2),(2,1))
x

array([[ 0.10557049,  0.17828254,  0.10557049,  0.17828254],
       [ 1.90767643, -1.10532562,  1.90767643, -1.10532562],
       [ 0.10557049,  0.17828254,  0.10557049,  0.17828254],
       [ 1.90767643, -1.10532562,  1.90767643, -1.10532562]])

In [86]:
#reverse order
x[:,::-1]

array([[ 0.17828254,  0.10557049,  0.17828254,  0.10557049],
       [-1.10532562,  1.90767643, -1.10532562,  1.90767643],
       [ 0.17828254,  0.10557049,  0.17828254,  0.10557049],
       [-1.10532562,  1.90767643, -1.10532562,  1.90767643]])

In [89]:
#sort by the first row
x[:,x[0].argsort()]

array([[ 0.10557049,  0.10557049,  0.17828254,  0.17828254],
       [ 1.90767643,  1.90767643, -1.10532562, -1.10532562],
       [ 0.10557049,  0.10557049,  0.17828254,  0.17828254],
       [ 1.90767643,  1.90767643, -1.10532562, -1.10532562]])