# Solving simultaneous equations with NumPy

Suppose we have the following system of simultaneous equations: 

x + 2y + 3z = 15  
3x + 2y + 4z = 20  
7x + 5y + 2z = 26 

We can represent these equations with a coefficient matrix, a vector of unknowns and a right-side vector. 

In [1]:
import numpy as np

A = np.array([[1,2,3],[3,2,4],[7,5,2]])
B = np.array([[15],[20],[20]])

In [2]:
A

array([[1, 2, 3],
       [3, 2, 4],
       [7, 5, 2]])

In [3]:
B

array([[15],
       [20],
       [20]])

In [4]:
solution = np.linalg.solve(A,B)

In [5]:
solution

array([[ 0.64516129],
       [ 1.61290323],
       [ 3.70967742]])

In [6]:
x, y, z = solution

In [7]:
#consider the first equation
x + 2*y + 3*z

array([ 15.])