# Sorting with NumPy

By default, np.sort uses a quick sort algorithm, though heapsort and mergesort are also available. 

In [1]:
import numpy as np

In [2]:
x = np.array([3,2,1,5,4])

In [3]:
#np.sort returns a sorted version of an array
np.sort(x)

array([1, 2, 3, 4, 5])

In [4]:
#The sort method sorts the array in place
x.sort()
x

array([1, 2, 3, 4, 5])

In [5]:
x = np.array([1,4,7,0,3])

In [6]:
#argsort returns the indicies of the sorted elements
np.argsort(x)

array([3, 0, 4, 1, 2], dtype=int64)

In [7]:
#this can be used to return a sorted array via fancy indexing
x[np.argsort(x)]

array([0, 1, 3, 4, 7])

### Sorting along  a specific axis

In [8]:
rand = np.random.RandomState(42)
X = rand.randint(0, 10, (4,6))
X

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

In [9]:
#sort along columns
np.sort(X, axis=0)

array([[2, 1, 4, 0, 1, 5],
       [5, 2, 5, 4, 3, 7],
       [6, 3, 7, 4, 6, 7],
       [7, 6, 7, 4, 9, 9]])

In [10]:
#sort along rows
np.sort(X, axis=1)

array([[3, 4, 6, 6, 7, 9],
       [2, 3, 4, 6, 7, 7],
       [1, 2, 4, 5, 7, 7],
       [0, 1, 4, 5, 5, 9]])

# Partitioning

The partition method returns a copy of an array where the kth element is positioned where it would be in a sorted array. All elements less than the kth value are placed on the left and the larger elements on the right. The elements on each side of the partition are in arbitrary order. 

In [11]:
X = np.array([0,2,1,5,4,7,11,3,8])

In [12]:
np.partition(X,3)

array([ 1,  0,  2,  3,  4,  7, 11,  5,  8])