# Specifying numpy ufunc output locations

In [19]:
import numpy as np

In [20]:
x = np.arange(5)

In [21]:
y = np.empty(5)

In [22]:
np.multiply(x, 10, out=y);

In [23]:
y

array([  0.,  10.,  20.,  30.,  40.])

In [24]:
y = np.zeros(10)

In [27]:
#write to every second element of y
np.power(2, x, out=y[::2])

array([  1.,   2.,   4.,   8.,  16.])

In [28]:
y

array([  1.,   0.,   2.,   0.,   4.,   0.,   8.,   0.,  16.,   0.])

In [31]:
z = np.zeros(10)
z[::2] = 2 ** x

In [34]:
"""This outputs the same, however, it first creates a temporary array to hold 2**x, followed by a second operation copying
those values into the z array. This is not as efficient as the out arguement.
"""
z

array([  1.,   0.,   2.,   0.,   4.,   0.,   8.,   0.,  16.,   0.])